#!/bin/bash

# 🎨 AGORA - Frontend Deployment on Vercel
# Connects to Render backend for full functionality

echo "🎨 AGORA Frontend Deployment Guide - Vercel"
echo "==========================================="
echo ""

echo "✅ Prerequisites:"
echo "  • Backend deployed to Render: https://agora-linera-backend.onrender.com"
echo "  • Code pushed to GitHub: mohamedwael201193/agora"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "OPTION 1: Deploy via Vercel Dashboard (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://vercel.com/new"
echo ""
echo "2. Sign in with GitHub"
echo ""
echo "3. Import Repository:"
echo "   • Click 'Import Project'"
echo "   • Select: mohamedwael201193/agora"
echo ""
echo "4. Project Settings:"
echo "   • Framework Preset: Vite"
echo "   • Root Directory: ./"
echo "   • Build Command: npm run build"
echo "   • Output Directory: dist"
echo ""
echo "5. Environment Variables - Add These:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Key                              | Value"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "VITE_NETWORK"
echo "conway"
echo ""
echo "VITE_AGORA_APP_ID"
echo "884e8b8e86f60309cdf11dd920f121331e1fd4b07533adebdb6d8c653c496905"
echo ""
echo "VITE_REGISTRY_CHAIN_ID"
echo "134f497810d118434d34ee63f46e0385e65ce0638bd682c719410065723fefbb"
echo ""
echo "VITE_CONWAY_REGISTRY_CHAIN_ID"
echo "134f497810d118434d34ee63f46e0385e65ce0638bd682c719410065723fefbb"
echo ""
echo "VITE_CONWAY_APPLICATION_ID"
echo "884e8b8e86f60309cdf11dd920f121331e1fd4b07533adebdb6d8c653c496905"
echo ""
echo "⭐ CRITICAL - Replace with your Render backend URL:"
echo ""
echo "VITE_LINERA_VALIDATOR_URL"
echo "https://agora-linera-backend.onrender.com"
echo ""
echo "VITE_NODE_URL"
echo "https://agora-linera-backend.onrender.com"
echo ""
echo "VITE_LINERA_FAUCET_URL"
echo "https://faucet.testnet-conway.linera.net"
echo ""
echo "VITE_ENABLE_DEVTOOLS"
echo "true"
echo ""
echo "VITE_ENABLE_STRESS_TEST"
echo "false"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "7. Wait 2-3 minutes for build..."
echo ""
echo "8. Get your URL:"
echo "   https://agora-xxx.vercel.app"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "OPTION 2: Deploy via Vercel CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "Installing Vercel CLI..."
    npm i -g vercel
fi

echo "Run deployment:"
echo ""
echo "  vercel"
echo ""
echo "Follow prompts:"
echo "  • Link to existing project? No"
echo "  • Project name? agora"
echo "  • Directory? ./"
echo "  • Override settings? No"
echo ""
echo "Then set environment variables:"
echo ""
echo "  vercel env add VITE_NETWORK"
echo "  vercel env add VITE_AGORA_APP_ID"
echo "  vercel env add VITE_REGISTRY_CHAIN_ID"
echo "  vercel env add VITE_LINERA_VALIDATOR_URL"
echo "  vercel env add VITE_NODE_URL"
echo "  (etc...)"
echo ""
echo "Deploy to production:"
echo ""
echo "  vercel --prod"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📋 POST-DEPLOYMENT CHECKLIST:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Test your deployment:"
echo ""
echo "1. Open: https://agora-xxx.vercel.app"
echo ""
echo "2. Check homepage loads"
echo ""
echo "3. Click wallet button - should connect"
echo ""
echo "4. Go to /marketplace - should show markets"
echo ""
echo "5. Try creating market in /foundry"
echo ""
echo "If errors occur:"
echo "  • Check Vercel environment variables"
echo "  • Verify Render backend is running"
echo "  • Check browser console for errors"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "🎯 QUICK REFERENCE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend (Render):"
echo "  URL: https://agora-linera-backend.onrender.com"
echo "  Linera service with Conway wallet"
echo ""
echo "Frontend (Vercel):"
echo "  URL: https://agora-xxx.vercel.app"
echo "  React + Vite app"
echo "  Connects to Render backend"
echo ""
echo "Environment Variables:"
echo "  VITE_LINERA_VALIDATOR_URL → Render backend URL"
echo "  VITE_NODE_URL → Same as above"
echo "  Other VITE_* → Conway testnet config"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "✅ DEPLOYMENT COMPLETE!"
echo ""
echo "Your app is now live on:"
echo "  Frontend: Vercel (global CDN, fast)"
echo "  Backend: Render (Conway testnet access)"
echo ""
echo "🎉 Full blockchain functionality online!"
echo ""

read -p "Open Vercel dashboard now? (y/n) " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    xdg-open "https://vercel.com/new" 2>/dev/null || open "https://vercel.com/new" 2>/dev/null || echo "Go to: https://vercel.com/new"
fi

echo ""
echo "📝 Need help? Check:"
echo "  • Vercel Docs: https://vercel.com/docs"
echo "  • Render Docs: https://render.com/docs"
echo "  • Linera Docs: https://docs.linera.io"
echo ""
